package com.example.vig.agent.provider

import com.example.vig.domain.interfaces.AIProvider
import com.example.vig.security.KeyStoreManager
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import okhttp3.OkHttpClient
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.IOException
import java.util.concurrent.TimeUnit

class GeminiProvider(private val keyStoreManager: KeyStoreManager) : AIProvider {

    private val client by lazy {
        OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(60, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .build()
    }

    private val api by lazy {
        Retrofit.Builder()
            .baseUrl("https://generativelanguage.googleapis.com/")
            .client(client)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(GeminiApi::class.java)
    }

    override suspend fun isConfigured(): Boolean {
        return !keyStoreManager.getApiKey().isNullOrBlank()
    }

    override suspend fun generateResponse(prompt: String): Result<String> {
        val apiKey = keyStoreManager.getApiKey()
            ?: return Result.failure(IllegalStateException("API key not configured. Add it in Settings."))

        return withContext(Dispatchers.IO) {
            try {
                val request = GeminiRequest(
                    contents = listOf(Content(parts = listOf(Part(text = prompt))))
                )
                val response = api.generateContent(apiKey, request)
                val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                if (text != null) {
                    Result.success(text)
                } else {
                    Result.failure(IllegalStateException("No response generated by the AI model."))
                }
            } catch (e: IOException) {
                Result.failure(IOException("Network error: ${e.message}", e))
            } catch (e: retrofit2.HttpException) {
                Result.failure(IOException("API error (${e.code()}): ${e.message()}", e))
            } catch (e: Exception) {
                Result.failure(e)
            }
        }
    }
}
